export enum NotificationType {
  WELCOME = 'WELCOME',
  COMMENT_UPVOTED = 'COMMENT_UPVOTED',
  COMMENT_DOWNVOTED = 'COMMENT_DOWNVOTED',
  COMMENT_REPLIED = 'COMMENT_REPLIED',
  AT_REFERENCE = 'AT_REFERENCE',
}
