export enum StatType {
  USERS = 'USERS',
  COMMENTS = 'COMMENTS',
  MESSAGES = 'MESSAGES',
  PROTECTIONS = 'PROTECTIONS',
  GROUPS = 'GROUPS',
  MARKETS = 'MARKETS',
  POSTS = 'POSTS',
  SUBJECT_CATEGORY = 'SUBJECT_CATEGORY'
}
